/* global define */
define(["jquery",
        "underscore",
        "backbone"],
  function($, _, Backbone, Product) {
    /**
     * @classdesc
     *
     * @class Product
     * @name Product
     * @constructor
    */
    var Product = Backbone.Model.extend(
      /** @lends Product.prototype */ {

      /**
      * The name of this type of model
      * @type {string}
      */
      type: "Product",

      /**
      * Default attributes for Product models
      * @name Product#defaults
      * @type {Object}
      * @property {string} id The autogenerated product identifier
      * @property {string} object The product object type name
      * @property {boolean} active The product visibility status (true or false)
      * @property {number} amount The product cost (in pence of the currency)
      * @property {string} caption A short caption that describes this Product
      * @property {string} currency The product currency code
      * @property {number} created The product creation timestamp (from the unix epoch in seconds)
      * @property {string} description A brief description of the product
      * @property {string} name The name of the product
      * @property {string} statementDescriptor The product statement descriptor shown on charge receipts
      * @property {string} type The product type, either a good or service
      * @property {string} unitLabel The product unit label used on invoices and charge receipts for type=service
      * @property {string} url The product URL that provides a product description
      * @property {object} metadata The product metadata hash of product features and other metadata
      */
      defaults: function(){
        return {
          id: "",
          object: "product",
          active: null,
          amount: 0,
          caption: "",
          currency: "USD",
          created: 0,
          description: "",
          name: "",
          statementDescriptor: "",
          type: "service",
          unitLabel: "",
          url: "",
          metadata: {}
        }
      }

    });

  return Product;
});
